config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index, :show, :new, :create]
  resources :articles, only: [:search, :show, :new, :create]
  devise_for :users, controllers: {
    sessions: 'sessions'
  }
  root to: 'categories#index'
  get 'search_articles', to: 'articles#search'
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, :text, :image, :categories, presence: true
  mount_uploader :image, ImageUploader
  validates :title, length: { minimum: 3, maximum: 30 }
  validates :text, length: { minimum: 10, maximum: 5000 }
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  has_many :votes
  has_many :voters, through: :votes
  has_many :users_vote, through: :votes, source: :user
  scope :highest_vote, -> { order(votes_count: :desc) }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  has_many :ordered_by_most_recent, -> { order(created_at: :desc).includes(:votes) },
           through: :article_categories, source: :article
  validates :name, presence: true,
                   uniqueness: true,
                   length: { minimum: 2, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         authentication_keys: [:name]
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  has_many :articles, dependent: :destroy
  has_many :votes
  has_many :liked_posts, through: :votes

  protected

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  def valid_password?
    false
  end

  def password_required?
    false
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true
  validates :user_id, uniqueness: { scope: :article_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:name)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :search_params, only: [:search]

  def show; end

  def new
    @article = Article.new
  end

  def search
    if @result
      respond_to do |format|
        format.js { render partial: 'articles/result' }
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Search field is blank'
        format.js { render partial: 'articles/result' }
      end
    end
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:notice] = 'Article successfully created'
      redirect_to @article
    else
      render :new
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image, category_ids: [])
  end

  def search_params
    @result = Article.where('title like ?', "%#{params[:search]}%") if params[:search] != ''
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @categories = Category.all
    @feature_article = Article.highest_vote.first
  end

  def show
    @category_articles = @category.articles.ordered_by_most_recent
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_category
    @category = Category.find_by(id: params[:id])
  end

  def category_params
    params.fetch(:category, {})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new; end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      sign_in(user)
      flash[:notice] = 'Logged in successfully'
      redirect_to root_path
    else
      flash.now[:notice] = 'Worng User-Name'
      render 'new'
    end
  end

  protected

  def after_confirmation_path_for(_resource_name, resource)
    token = resource.send(:set_reset_password_token)
    edit_password_path(resource, reset_password_token: token)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :up_vote_params, only: [:create]
  before_action :down_vote_params, only: [:destroy]

  def create
    if @vote.save
      redirect_to request.referer
    else
      flash[:notice] = 'Something when wrong'
    end
  end

  def destroy
    if @vote
      @vote.destroy
      redirect_to request.referer
    else
      flash[:notice] = 'Something when wrong'
    end
  end

  private

  def up_vote_params
    @vote = current_user.votes.new(article_id: params[:article_id])
  end

  def down_vote_params
    @vote = Vote.find_by(id: params[:id], user: current_user, article_id: params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def upvote_or_downvote_btn(article)
    vote = Vote.find_by(article: article, user: current_user)
    if vote
      link_to('<i class="fa fa-thumbs-down"></i>'.html_safe,
              article_vote_path(id: vote.id, article_id: article.id), method: :delete)
    else
      link_to('<i class="fa fa-thumbs-up"></i>'.html_safe, article_votes_path(article_id: article.id), method: :post)
    end
  end

  def cp(path)
    'current-color' if current_page?(path)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-11">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: article, class: "shadow p-3 article-form form rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label article-form-text-color font-weight-bold" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :text, 'description', class: "col-2 col-form-label article-form-text-color font-weight-bold" %>
          <div class="col-10"> 
            <%= f.text_area :text, rows: 8, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :Categories, class: "col-2 col-form-label article-form-text-color font-weight-bolder" %>
          <div class="col-10 mt-2"> 
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "d-inline input_checkbox mr-3 text-white font-weight-bold") {cb.check_box(class: "checkbox mr-1") + cb.text } %>
            <% end %>
            <%= f.label :image, class: "font-weight-bold article-form-text-color ml-3 d-inline" %>
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "text-white select-image d-inline" %>
          </div> 
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn text-white btn-background-color btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div> 

app/views/articles/_result.html.erb
<div class="col-sm-12">
  <%= render 'layouts/messages' %>
</div>

<% if @result %> 
  <table class="table table-bordered table-color">
    <thead>
      <% @result.each do |result| %>
        <tr>
          <th scope="col" class="text-white text-center alert alert-dismissible fade show" role="alert">
            <%= link_to article_path(result), class: "text-white" do %>
              <%= truncate(result.title , length: 30)%>
            <% end %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </th>
        </tr> 
      <% end %>
    </thead>
  </table>
<% end %>

app/views/articles/_result.js.erb
document.querySelector('#result').innerHTML =  '<%= j render 'articles/result.html' %>'

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class= 'container w-50 pr-n5 pl-n5 text-article-show-page mt-2'>
  <div class= 'img-article'>
    <%= image_tag @article.image.url, class: 'element-show element'%>
  </div>
  <div class="mb-5 ">
    <h1 class=" text-center font-weight-bold text-title mt-3 mb-5 "><%= @article.title%></h1>
    <p class="font-weight-bolder"><%= @article.text%></p>
  </div>
</div>
<div class='container upvote-downvote mb-5'>
  <span class= 'font-weight-bold'>Author : <strong class="current-color" ><%= @article.user.name %> </strong></span>
  <span class= "ml-3 "><%= pluralize(@article.votes.count, 'Vote') %></span>
  <%= upvote_or_downvote_btn(@article) %>
</div>

app/views/categories/_categories.html.erb
<% Category.all.each do |category|%>
  <li class="nav-item">
    <li><%= link_to category.name, category_path(category.id), class: "#{cp(category_path(category.id))} nav-link font-weight-bold" %></li>
  </li>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class = 'container-fluid'>
  <div class= 'row'>
    <div class= 'col sm-12 main-img p-0'>
      <% if @feature_article %>
        <%= image_tag(@feature_article.image ? @feature_article.image.url : '', class: 'img') %>
        <div class="bottom-left-main">
          <h6 class= 'current-color font-weight-bold ml-3'><%= @feature_article.title ? @feature_article.title : '' %></h6>
          <p class= 'text-white font-weight-bold ml-3'><%= truncate(@feature_article.text , length: 350)%></p>
        </div> 
      <% end %>
    </div>
  </div>
</div>
  <!-- categories -->
<div id="portfolio">
  <div class="container-fluid p-0">
    <div class="row no-gutters">
      <% Category.includes(:ordered_by_most_recent).each do |category|%>
        <% subcategories = category.ordered_by_most_recent.first %>
        <div class="col-sm-3 bg">
          <div class="element">
            <%= image_tag( subcategories.present? ? subcategories.image.url : '', class: 'image element"') %>
          </div>
          <%= link_to category_path(category.id) do %>
            <div class="top-left">
              <h6 class= 'font-weight-bold text-white img-bottom'><%= category.name %></h6>
            </div>
            <div class="bottom-left">
              <p class= 'text-white font-weight-bold'><%= subcategories.present? ? subcategories.title : '' %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="articles">
  <% @category_articles.each do |article| %>
    <%= link_to article_path(article), class: 'article' do %>
          <div>
            <%= image_tag(article.image.url, class: 'article-img element') %>
          </div>
          <div class="card-body">
            <h5 class='category-name font-weight-bolder'><%= @category.name %></h5>
            <h5 class="card-text font-weight bold"><%= truncate(article.title, length: 55) %></h5>
            <p class="card-text"><%= truncate(article.text, length: 315) %></p>
            <%= pluralize(article.votes_count, 'Vote') %> 
            <%= fa_icon "thumbs-up" %>
            <p>
            </p>
          </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer bg-light" id="sticky-footer">
  <div class="container-fluid p-0">
    <div class="row">
    <div class="col-sm-2 h-100 text-center text-sm-left my-auto">
      <ul class="list-inline mt-2 unstyled">
        <li class="list-inline-item ml-3">
        <h4 class="pt-2 text-white">Dev-<strong class="logo">BLOG</strong></h4>
        </li>
      </ul>
      </div>
      <div class="col-sm-7 h-100 text-center text-sm-left pl-5 my-auto">
        <ul class="list-inline font-size mt-2 unstyled">
          <li class="list-inline-item">
            <a class='current-color' href="#">Privacy Policy</a>
          </li>
          <li class="list-inline-item">
            <a class='current-color' href="#">Terms and condition</a>
          </li>
          <li class="list-inline-item text-white">
            Copyright 2014.All rights reserved
          </li>
        </ul>
      </div>
      <div class="col-sm-3 h-100 text-center text-sm-right my-auto pr-4">
        <ul class="list-inline font-size mt-2">
          <li class="list-inline-item text-white">Connect with us at:</li>
          <li class="list-inline-item ">
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fa fa-twitter-square"></i>
            </a>
          </li>
          <li class="list-inline-item mr-2">
            <a href="#">
              <i class="fa fa-instagram"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_login.html.erb
 <% if user_signed_in?  %>
  <li class="nav-item">
    <%= link_to 'Logout', destroy_user_session_path, class: "nav-link font-weight-bold ml-n2 mr-2", method: :delete %>
  </li>
    <% else %>
  <li class="nav-item">
    <%= link_to 'Login', new_user_session_path, class: 'nav-link mr-n2 font-weight-bold' %>
  </li>
  <li class="nav-item nav-link font-weight-bold">|</li>
  <li class="nav-item" id="border-l">
    <%= link_to 'Register', new_user_registration_path, class: 'nav-link ml-n2 font-weight-bold' %>
  </li>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success' id='flash-messages'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
	<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger' id='flash-messages'>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
	<%= alert %>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white nav-bottom">
  <h4 class="pt-2">Dev-<strong class="logo">BLOG</strong></h4>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav font-size home-links">
     <% if user_signed_in? %>
      <li class="nav-item" >
        <%= link_to 'Home', root_path, class: "#{cp(root_path)} nav-link font-weight-bold"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Create an Article', new_article_path, class: "#{cp(new_article_path)} nav-link font-weight-bold" %>
      </li>
        <%= render 'categories/categories'%>
      <li class="nav-item"></li>
       <% end %>
    </ul>
    <ul class="navbar-nav font-size ml-auto search-position">
      <% if user_signed_in? %>
        <li class='search-form' ><%= render 'layouts/search_form' %></li>
      <% end %>
     <li><%= render 'layouts/login'%></li>
    </ul>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="form-group row ">
    <div class="col-sm-9">
      <%= text_field_tag :stock, params[:stock], autofocus: true, class: "form-control mr-n5", placeholder: 'Search for stock' %>
    </div>
    <div class="col-sm-3">
      <%= button_tag type: :submit, class: "btn btn-success ml-n5 form-margin-left" do %>
        <%= fa_icon 'search' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_search_form.html.erb
<%= form_tag search_articles_path, remote: true, method: :get do %>
  <div class="form-group row ">
    <div class="col-sm-10 search-form">
      <%= text_field_tag :search, params[:search], autofocus: true, class: "form-control", placeholder: 'Search for blogs' %>
    </div>
    <div class="col-sm-1">
      <%= button_tag type: :submit, class: "btn btn-secondary form-margin-left" do %>
        <%= fa_icon 'search' %>
      <% end %>
    </div>
  </div>
<% end %>

<div id="result"> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="body">
    <%= render 'layouts/navbar' %>
    <div class="page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
      <div class="push"></div>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved.</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>